### ISSUE TITLE
typo in util.py

### ISSUE THREAD

**Issue by ntuLC** [pymatting/pymatting#17]
in file util/util.py line 487-491:

```
    if is_fg.sum() == 0:
        raise ValueError("Trimap did not contain background values (values = 0)")

    if is_bg.sum() == 0:
        raise ValueError("Trimap did not contain foreground values (values = 1)")
```

Looks the place of two error messages should be swapped

**Comment by tuelwer** [comment]
Of course! Thank you for opening the issue, @ntuLC! I fixed the typo in commit c875f35ea5bb9fba3ded458cd88a5b827d8fb56d.
