### ISSUE TITLE
typo in knn_laplacian?

### ISSUE THREAD

**Issue by hding2455** [pymatting/pymatting#18]
This repo really helps, Thank you!

But, I just find that the comment said the distance_weights "Weight of distance in feature vector, defaults to `[2.0, 1.0]`." but in the def line, the distance_weights distance_weights=[2.0, 0.1]. Is there a typo in definition or the comment. Which one is more generalized setting?

**Comment by tuelwer** [comment]
We are glad to hear that!

Thank you for the spot! The docstring was incorrect. I fixed it in 00e6ff5652092a87cb027879d35c9d2a747a20f7. We found `distance_weights=[2.0, 0.1]` for `n_neighbors=[20, 10]` to work well in practice. However, this depends on the images you are using. Feel free to share your experience, if you find a setting that works better on your use-case.
