### ISSUE TITLE
Matting without Trimap

### ISSUE THREAD

**Issue by bluesky314** [pymatting/pymatting#22]
Thanks for your amazing library. I would like to know if any method can support only a rgb input without a trimap. If not, may I ask why is there such a strong need for trimaps and why the algorithms have difficulty considering everything as part of the trimap region. I am working on a deep learning trimap less approach so am interested in gaining your thoughts on this issue.

**Comment by 99991** [comment]
With trimaps, you have more control about what to cut out from the image. For example, if you have a photo of multiple objects, the algorithm can not know which object it should cut out. The trimap is used to decide that.

But if you can make some assumptions about the image, for example the image only contains a single person or the object of interest is always at the center of the image in front of all other objects, then deep learning methods can work without a trimap.
