### ISSUE TITLE
Pymatting Image not producing good results. Is here something wrong?

### ISSUE THREAD

**Issue by kashyappiyush1998** [pymatting/pymatting#26]
Orignal image, trimap, output image is - 
![woman-standing-and-doing-pose-beside-lake-1468379-removebg-preview](https://user-images.githubusercontent.com/35548940/88458056-ca2d1080-cea8-11ea-9034-3402bf3700ed.png) 
![trimap_image_improved](https://user-images.githubusercontent.com/35548940/88458186-e41b2300-cea9-11ea-94ff-ff158307d18e.png) ![lemur_cutout](https://user-images.githubusercontent.com/35548940/88458094-0bbdbb80-cea9-11ea-8c2f-cf7521aeb20b.png)

Hair's for which I was using Pymatting are blurred. Is this some fault from my side? 
Thanks.

**Comment by 99991** [comment]
I do not understand what you are trying to achieve here. Your [input image](https://user-images.githubusercontent.com/35548940/88458056-ca2d1080-cea8-11ea-9034-3402bf3700ed.png) has an alpha channel already, so there is no need to cut it out again.

We are using the PILLOW library for image loading and automatically convert all input images to RGB, but when you pass in an RGBA image, the alpha channel will simply be discarded and the input image will not be a good input for alpha matting.

You can test this yourself with the following code:

```python
from pymatting import load_image, save_image

rgb = load_image("input.png", "RGB")
save_image("rgb.png", rgb)
```

**Comment by kashyappiyush1998** [comment]
I am trying to achieve background removal, input will not be this accurate all the time, that is why I need to have matted image.

**Comment by 99991** [comment]
Since your input image is in RGBA format instead of RGB, the pillow library converts your input image to an image that looks almost like your output image. For this image, the background has the same color as the hair, so alpha matting can not work here.

To solve this, provide an RGB input image instead of an RGBA input image.
