### ISSUE TITLE
[BUG 🐛]Just a small typo in estimate_alpha_lkm.py

### ISSUE THREAD

**Issue by ntuLC** [pymatting/pymatting#29]
In file estimate_alpha_lkm.py, L9

`Estimate alpha from an input image and an input trimap using Learning Based Digital Matting as proposed by :cite:he2010fast.`

I guess the paper name was intended to be _Fast matting using large kernel matting laplacian matrices_?😉

**Comment by 99991** [comment]
You are absolutely correct, thank you for spotting this typo.

Has been fixed now:

https://github.com/pymatting/pymatting/blob/81eaf5fd3bc3deae3cf1a7345194b00080ac61e4/pymatting/alpha/estimate_alpha_lkm.py#L9
