### ISSUE TITLE
[Question❓] Question regarding output of advanced example

### ISSUE THREAD

**Issue by ghazni123** [pymatting/pymatting#32]
Thank you for your efforts. I have successfully built the package and was able to execute few examples by following advanced example on https://pymatting.github.io/examples.html and have request for info.

I am attaching set of images to elaborate for what I am seeing and advice on how to improve the results.

1: original.png: it is the original file
2: target.png: this file is the manual alpha from photoshop (i was aiming for - might be ambitious)
3: color_bleeding.png, grid.png and cutout.png are the outputs of the pymatting package
4: initial_mask.jpg: that is the rough mask generated by the segmentation framework i.e. detectron2
5: trimap.png: that was generated by following function
def gen_trimap(alpha):
    k_size = random.choice(range(1, 5))
    iterations = np.random.randint(1, 20)
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (k_size, k_size))
    dilated = cv2.dilate(alpha, kernel, iterations)
    eroded = cv2.erode(alpha, kernel, iterations)
    trimap = np.zeros(alpha.shape)
    trimap.fill(128)
    trimap[eroded >= 255] = 255
    trimap[dilated <= 0] = 0
    return trimap

Q1: is there a way the internal contours can be removed? or maybe not until those are present in trimap as well?

Q2: advice on what do i need to do in pymatting package to improve the alpha around external contours or hairs etc. given input image, rough mask from segmentation framwork and trimap (calculated in SW like above)?

Q3: could it also be the case that my testcase is more ambitious and pymatting is more suitable for object with sharp edges e.g. cars

Thank you.

**Comment by 99991** [comment]
It is hard to understand what you are trying to do. Maybe it would have been easier to write the image description next to the respective image? Currently, I can not tell which description belongs to which image.

Anyway, the input has to be an image + a trimap. I can not find any trimap here. A trimap needs three values:

1. White (foreground)
2. Black (background)
3. Gray (values to fill in with pymatting)

There also are some images with blocky artifacts, which are probably caused by JPG compression. JPG should not be used for image processing tasks because it reduces image quality.

![grid](https://user-images.githubusercontent.com/18725165/97354389-92fa4100-1895-11eb-9b2e-4e8bd322e0b5.png)

From top left to bottom right: Input image, input trimap, computed alpha matte, computed cutout.

**Comment by ghazni123** [comment]
Hi Thomas,

Sincere apologies for the disjoint text and images. I was expecting filenames will stay but they disappeared after I uploaded.

Many thanks for your reply. Yes I understand the process and required inputs in order to get alpha. I am trying to automate the creation of trimap using software. As you mentioned that input and trimap both are required in order to get alpha. So to the best of my understanding there are two methods to get trimap:

**Method 1:** finding trimap manually using photoshop and passing it to pymatting to get alpha

**Method 2:** use segmentation framework to calculate rough alpha (or mask) and pass that rough alpha to software function (like the one in my previous message or variation of it using different dilate/erode) and calculate trimap. Pass software calculated trimap to pymatting to get relatively accurate alpha

"Method 2" as described is just the summary of my previous message. My suspicion is that the example you have shown in your reply is most likely using the "Method 1"

The question perhaps can be rephrased as:
Can we use "Method 2" to get alpha of the quality which same/similar to "Method 1"?

Thank you.

**Comment by 99991** [comment]
The trimap in my reply was hand-drawn.

> Can we use "Method 2" to get alpha of the quality which same/similar to "Method 1"?

Not without further assumptions. For example, there could be multiple subjects in an image and the segmentation framework could segment the wrong one, so there is not much that could be done afterwards.

With Method 1, the alpha matte could be inaccurate as well if the trimap was bad, but you can go back and refine it for a better result.

Also it might be tricky to get a good trimap from the segmentation, especially if there are large translucent regions.

If you want to produce an alpha matte without user input, you will probably get better results by training a neural network end-to-end on a custom dataset with the specific subjects that you are expecting for your application. See also this issue with a similar problem statement: https://github.com/pymatting/pymatting/issues/33
