### ISSUE TITLE
[BUG 🐛] the results between the function "estimate_foreground_ml" and "estimate_foreground_ml_cupy" were different 

### ISSUE THREAD

**Issue by onefish51** [pymatting/pymatting#39]
**Bug description**
I estimated the foreground by "pymatting.foreground.estimate_foreground_ml" and "pymatting.foreground.estimate_foreground_ml_cupy". But I found the results between the function "estimate_foreground_ml" and "estimate_foreground_ml_cupy" were different . And there were something wrong in the output `estimate_foreground_ml_cupy` estimated!

**Images**

- input image :
![test](https://user-images.githubusercontent.com/21029719/111269291-60e15400-8669-11eb-83ac-6f15cc438ecb.jpg)

- output image by `estimate_foreground_ml`:
![human_ml](https://user-images.githubusercontent.com/21029719/111269296-6343ae00-8669-11eb-83b4-217ccbb787d7.png)

- output image by `estimate_foreground_ml_cupy`:
![human_cupy](https://user-images.githubusercontent.com/21029719/111269309-68a0f880-8669-11eb-91af-201c29c29ff2.png)

- wrong `estimate_foreground_ml_cupy` estimated: "the ear with black contours"
![image](https://user-images.githubusercontent.com/21029719/111269344-7787ab00-8669-11eb-8fb4-3d78a1f25870.png)

**Comment by 99991** [comment]
`estimate_foreground_ml` is a bit different from `estimate_foreground_ml_cupy`. The GPU implementation has to do everything in parallel, which is why it has to compute updated foreground values from foreground values of the previous iteration, while the CPU implementation can already use the updated foreground values from the same iteration.

You can increase the parameter `n_big_iterations` from 2 to 3 to get a better result:

```python
foreground = estimate_foreground_ml_cupy(image, alpha, n_big_iterations=3)
```

Here is a comparison for different values:

![iterations](https://user-images.githubusercontent.com/18725165/111274762-af74fb00-8635-11eb-9f5b-e5fa2d5bd9d2.png)


```python
from pymatting import *
from pymatting.foreground.estimate_foreground_ml_cupy import estimate_foreground_ml_cupy
import matplotlib.pyplot as plt

"""
wget https://user-images.githubusercontent.com/21029719/111269291-60e15400-8669-11eb-83ac-6f15cc438ecb.jpg
wget https://user-images.githubusercontent.com/21029719/111269296-6343ae00-8669-11eb-83b4-217ccbb787d7.png
"""

image = load_image("111269291-60e15400-8669-11eb-83ac-6f15cc438ecb.jpg", "RGB")
output = load_image("111269296-6343ae00-8669-11eb-83b4-217ccbb787d7.png", "RGBA")
alpha = output[:, :, 3]

plt.figure(figsize=(6, 8))
for n in [2, 3, 4, 5]:
    foreground = estimate_foreground_ml_cupy(image, alpha, n_big_iterations=n)
    composite = stack_images(foreground, alpha)

    ear = composite[180:280, 80:160]

    plt.subplot(2, 2, n - 1)
    plt.title(f"{n} iterations")
    plt.imshow(ear, cmap='gray')
    plt.axis('off')
plt.savefig("iterations.png")
plt.show()
```


It might also help to estimate the alpha matte with a larger `radius` or `epsilon` value. I can not test that because of missing trimap and jpeg-compressed input image. Maybe it does not work at all or maybe different values for `radius` or `epsilon` work better.

```python
alpha = estimate_alpha_lkm(image, trimap, laplacian_kwargs=dict(radius=10, epsilon=1e-5))
```

**Comment by onefish51** [comment]
> `estimate_foreground_ml` is a bit different from `estimate_foreground_ml_cupy`. The GPU implementation has to do everything in parallel, which is why it has to compute updated foreground values from foreground values of the previous iteration, while the CPU implementation can already use the updated foreground values from the same iteration.
> 
> You can increase the parameter `n_big_iterations` from 2 to 3 to get a better result:
> 
> ```python
> foreground = estimate_foreground_ml_cupy(image, alpha, n_big_iterations=3)
> ```
> 
> Here is a comparison for different values:
> 
> ![iterations](https://user-images.githubusercontent.com/18725165/111274762-af74fb00-8635-11eb-9f5b-e5fa2d5bd9d2.png)
> 
> ```python
> from pymatting import *
> from pymatting.foreground.estimate_foreground_ml_cupy import estimate_foreground_ml_cupy
> import matplotlib.pyplot as plt
> 
> """
> wget https://user-images.githubusercontent.com/21029719/111269291-60e15400-8669-11eb-83ac-6f15cc438ecb.jpg
> wget https://user-images.githubusercontent.com/21029719/111269296-6343ae00-8669-11eb-83b4-217ccbb787d7.png
> """
> 
> image = load_image("111269291-60e15400-8669-11eb-83ac-6f15cc438ecb.jpg", "RGB")
> output = load_image("111269296-6343ae00-8669-11eb-83b4-217ccbb787d7.png", "RGBA")
> alpha = output[:, :, 3]
> 
> plt.figure(figsize=(6, 8))
> for n in [2, 3, 4, 5]:
>     foreground = estimate_foreground_ml_cupy(image, alpha, n_big_iterations=n)
>     composite = stack_images(foreground, alpha)
> 
>     ear = composite[180:280, 80:160]
> 
>     plt.subplot(2, 2, n - 1)
>     plt.title(f"{n} iterations")
>     plt.imshow(ear, cmap='gray')
>     plt.axis('off')
> plt.savefig("iterations.png")
> plt.show()
> ```
> 
> It might also help to estimate the alpha matte with a larger `radius` or `epsilon` value. I can not test that because of missing trimap and jpeg-compressed input image. Maybe it does not work at all or maybe different values for `radius` or `epsilon` work better.
> 
> ```python
> alpha = estimate_alpha_lkm(image, trimap, laplacian_kwargs=dict(radius=10, epsilon=1e-5))
> ```

I got it ! 
And alpha is here！
![alpha](https://user-images.githubusercontent.com/21029719/111275597-47440a80-8671-11eb-8ffc-0eafd6fa297d.png)
