### ISSUE TITLE
Speedup[Question❓]

### ISSUE THREAD

**Issue by hoolizou** [pymatting/pymatting#42]
Thank you very much for your work.
I want to know whether can use GPU to accelerate matrix operation！

**Comment by 99991** [comment]
You can use [CuPy](https://github.com/cupy/cupy) to solve the linear system in the [expert example](https://raw.githubusercontent.com/pymatting/pymatting/master/examples/expert_example.py) (using the [lemur test images](https://github.com/pymatting/pymatting/tree/master/data/lemur)).

```python3
from pymatting import *
import numpy as np
import scipy.sparse
import cupy
import cupyx.scipy.sparse.linalg
import time

scale = 1.0

image = load_image("lemur.png", "RGB", scale, "box")
trimap = load_image("lemur_trimap.png", "GRAY", scale, "nearest")

# height and width of trimap
h, w = trimap.shape[:2]

# calculate laplacian matrix
L = cf_laplacian(image)

# decompose trimap
is_fg, is_bg, is_known, is_unknown = trimap_split(trimap)

# constraint weight
lambda_value = 100.0

# build constraint pixel selection matrix
c = lambda_value * is_known
C = scipy.sparse.diags(c)

# build constraint value vector
b = lambda_value * is_fg

# build linear system
A = L + C

start_time = time.perf_counter()

# Build incomplete cholesky preconditioner
A = A.tocsr()
A.sum_duplicates()
M = ichol(A)

# solve linear system with conjugate gradient descent
x_cpu = cg(A, b, M=M)

elapsed_time = time.perf_counter() - start_time

print("Solving the linear system on CPU took", elapsed_time, "seconds")

start_time = time.perf_counter()

# build jacobi preconditioner
M = scipy.sparse.diags(1.0 / A.diagonal())

# transfer linear system from RAM to GPU memory
M = cupyx.scipy.sparse.csr_matrix(M)
A = cupyx.scipy.sparse.csr_matrix(A)
b = cupy.asarray(b)

# solve linear system
x_gpu, error = cupyx.scipy.sparse.linalg.cg(A, b, M=M, tol=1e-7)
assert(error == 0)

# transfer result to RAM from GPU memory
x_gpu = cupy.asnumpy(x_gpu)

elapsed_time = time.perf_counter() - start_time

print("Solving the linear system on GPU took", elapsed_time, "seconds")

print("Solution difference (mean squared error):", np.mean(np.square(x_gpu - x_cpu)))

# clip and reshape result vector
alpha = np.clip(x_gpu, 0.0, 1.0).reshape(h, w)

save_image("lemur_alpha.png", alpha)
```

However, there are some issues with this. The fastest method to solve these linear systems is conjugate gradient descent (CG) with a good preconditioner. The best preconditioner we found so far is the incomplete thresholded Cholesky preconditioner. With this preconditioner, CG converges in just a few iterations. The problem here is that this preconditioner can not be computed well in parallel, but GPUs are only fast for parallel tasks.

There are other preconditioners, like for example the Jacobi preconditioner, which can be computed in parallel. But with this preconditioner, CG takes hundreds or thousands of iterations to converge.

Another problem is that NVIDIA gaming GPUs have 64 times worse double precision performance compared to single precision (see [https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units#GeForce_30_series](https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units#GeForce_30_series) for reference), probably to make people buy the expensive premium GPUs. Unfortunately, alpha matting might run into convergence issues with single precision floating point.

Anyway, I get the following numbers with the code from above using an Intel Xeon Gold 6134 CPU and a Tesla-P100 GPU:

```
Solving the linear system on CPU took 1.2201764308847487 seconds
Solving the linear system on GPU took 1.1049338467419147 seconds
Solution difference (mean squared error): 7.32248139148202e-07
```

The GPU is slightly faster, but also costs twice as much as the CPU, which is running single threaded, so it still has performance to spare. Numba does not yet support multi-threading with ahead-of-time-compiled code, but when it does in the future, the CPU solver will probably be faster than the GPU solver.

We also provide a V-Cycle preconditioner, which could be implemented to run in parallel on the GPU and has reasonable convergence properties. Unfortunately, the memory cost is huge, especially for large images, so it is probably not worth the trouble.

**Comment by hoolizou** [comment]
> You can use [CuPy](https://github.com/cupy/cupy) to solve the linear system in the [expert example](https://raw.githubusercontent.com/pymatting/pymatting/master/examples/expert_example.py) (using the [lemur test images](https://github.com/pymatting/pymatting/tree/master/data/lemur)).
> 
> ```python
> from pymatting import *
> import numpy as np
> import scipy.sparse
> import cupy
> import cupyx.scipy.sparse.linalg
> import time
> 
> scale = 1.0
> 
> image = load_image("lemur.png", "RGB", scale, "box")
> trimap = load_image("lemur_trimap.png", "GRAY", scale, "nearest")
> 
> # height and width of trimap
> h, w = trimap.shape[:2]
> 
> # calculate laplacian matrix
> L = cf_laplacian(image)
> 
> # decompose trimap
> is_fg, is_bg, is_known, is_unknown = trimap_split(trimap)
> 
> # constraint weight
> lambda_value = 100.0
> 
> # build constraint pixel selection matrix
> c = lambda_value * is_known
> C = scipy.sparse.diags(c)
> 
> # build constraint value vector
> b = lambda_value * is_fg
> 
> # build linear system
> A = L + C
> 
> start_time = time.perf_counter()
> 
> # Build incomplete cholesky preconditioner
> A = A.tocsr()
> A.sum_duplicates()
> M = ichol(A)
> 
> # solve linear system with conjugate gradient descent
> x_cpu = cg(A, b, M=M)
> 
> elapsed_time = time.perf_counter() - start_time
> 
> print("Solving the linear system on CPU took", elapsed_time, "seconds")
> 
> start_time = time.perf_counter()
> 
> # build jacobi preconditioner
> M = scipy.sparse.diags(1.0 / A.diagonal())
> 
> # transfer linear system from RAM to GPU memory
> M = cupyx.scipy.sparse.csr_matrix(M)
> A = cupyx.scipy.sparse.csr_matrix(A)
> b = cupy.asarray(b)
> 
> # solve linear system
> x_gpu, error = cupyx.scipy.sparse.linalg.cg(A, b, M=M, tol=1e-7)
> assert(error == 0)
> 
> # transfer result to RAM from GPU memory
> x_gpu = cupy.asnumpy(x_gpu)
> 
> elapsed_time = time.perf_counter() - start_time
> 
> print("Solving the linear system on GPU took", elapsed_time, "seconds")
> 
> print("Solution difference (mean squared error):", np.mean(np.square(x_gpu - x_cpu)))
> 
> # clip and reshape result vector
> alpha = np.clip(x_gpu, 0.0, 1.0).reshape(h, w)
> 
> save_image("lemur_alpha.png", alpha)
> ```
> 
> However, there are some issues with this. The fastest method to solve these linear systems is conjugate gradient descent (CG) with a good preconditioner. The best preconditioner we found so far is the incomplete thresholded Cholesky preconditioner. With this preconditioner, CG converges in just a few iterations. The problem here is that this preconditioner can not be computed well in parallel, but GPUs are only fast for parallel tasks.
> 
> There are other preconditioners, like for example the Jacobi preconditioner, which can be computed in parallel. But with this preconditioner, CG takes hundreds or thousands of iterations to converge.
> 
> Another problem is that NVIDIA gaming GPUs have 64 times worse double precision performance compared to single precision (see https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units#GeForce_30_series for reference), probably to make people buy the expensive premium GPUs. Unfortunately, alpha matting might run into convergence issues with single precision floating point.
> 
> Anyway, I get the following numbers with the code from above using an Intel Xeon Gold 6134 CPU and a Tesla-P100 GPU:
> 
> ```
> Solving the linear system on CPU took 1.2201764308847487 seconds
> Solving the linear system on GPU took 1.1049338467419147 seconds
> Solution difference (mean squared error): 7.32248139148202e-07
> ```
> 
> The GPU is slightly faster, but also costs twice as much as the CPU, which is running single threaded, so it still has performance to spare. Numba does not yet support multi-threading with ahead-of-time-compiled code, but when it does in the future, the CPU solver will probably be faster than the GPU solver.
> 
> We also provide a V-Cycle preconditioner, which could be implemented to run in parallel on the GPU and has reasonable convergence properties. Unfortunately, the memory cost is huge, especially for large images, so it is probably not worth the trouble.



> You can use [CuPy](https://github.com/cupy/cupy) to solve the linear system in the [expert example](https://raw.githubusercontent.com/pymatting/pymatting/master/examples/expert_example.py) (using the [lemur test images](https://github.com/pymatting/pymatting/tree/master/data/lemur)).
> 
> ```python
> from pymatting import *
> import numpy as np
> import scipy.sparse
> import cupy
> import cupyx.scipy.sparse.linalg
> import time
> 
> scale = 1.0
> 
> image = load_image("lemur.png", "RGB", scale, "box")
> trimap = load_image("lemur_trimap.png", "GRAY", scale, "nearest")
> 
> # height and width of trimap
> h, w = trimap.shape[:2]
> 
> # calculate laplacian matrix
> L = cf_laplacian(image)
> 
> # decompose trimap
> is_fg, is_bg, is_known, is_unknown = trimap_split(trimap)
> 
> # constraint weight
> lambda_value = 100.0
> 
> # build constraint pixel selection matrix
> c = lambda_value * is_known
> C = scipy.sparse.diags(c)
> 
> # build constraint value vector
> b = lambda_value * is_fg
> 
> # build linear system
> A = L + C
> 
> start_time = time.perf_counter()
> 
> # Build incomplete cholesky preconditioner
> A = A.tocsr()
> A.sum_duplicates()
> M = ichol(A)
> 
> # solve linear system with conjugate gradient descent
> x_cpu = cg(A, b, M=M)
> 
> elapsed_time = time.perf_counter() - start_time
> 
> print("Solving the linear system on CPU took", elapsed_time, "seconds")
> 
> start_time = time.perf_counter()
> 
> # build jacobi preconditioner
> M = scipy.sparse.diags(1.0 / A.diagonal())
> 
> # transfer linear system from RAM to GPU memory
> M = cupyx.scipy.sparse.csr_matrix(M)
> A = cupyx.scipy.sparse.csr_matrix(A)
> b = cupy.asarray(b)
> 
> # solve linear system
> x_gpu, error = cupyx.scipy.sparse.linalg.cg(A, b, M=M, tol=1e-7)
> assert(error == 0)
> 
> # transfer result to RAM from GPU memory
> x_gpu = cupy.asnumpy(x_gpu)
> 
> elapsed_time = time.perf_counter() - start_time
> 
> print("Solving the linear system on GPU took", elapsed_time, "seconds")
> 
> print("Solution difference (mean squared error):", np.mean(np.square(x_gpu - x_cpu)))
> 
> # clip and reshape result vector
> alpha = np.clip(x_gpu, 0.0, 1.0).reshape(h, w)
> 
> save_image("lemur_alpha.png", alpha)
> ```
> 
> However, there are some issues with this. The fastest method to solve these linear systems is conjugate gradient descent (CG) with a good preconditioner. The best preconditioner we found so far is the incomplete thresholded Cholesky preconditioner. With this preconditioner, CG converges in just a few iterations. The problem here is that this preconditioner can not be computed well in parallel, but GPUs are only fast for parallel tasks.
> 
> There are other preconditioners, like for example the Jacobi preconditioner, which can be computed in parallel. But with this preconditioner, CG takes hundreds or thousands of iterations to converge.
> 
> Another problem is that NVIDIA gaming GPUs have 64 times worse double precision performance compared to single precision (see https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units#GeForce_30_series for reference), probably to make people buy the expensive premium GPUs. Unfortunately, alpha matting might run into convergence issues with single precision floating point.
> 
> Anyway, I get the following numbers with the code from above using an Intel Xeon Gold 6134 CPU and a Tesla-P100 GPU:
> 
> ```
> Solving the linear system on CPU took 1.2201764308847487 seconds
> Solving the linear system on GPU took 1.1049338467419147 seconds
> Solution difference (mean squared error): 7.32248139148202e-07
> ```
> 
> The GPU is slightly faster, but also costs twice as much as the CPU, which is running single threaded, so it still has performance to spare. Numba does not yet support multi-threading with ahead-of-time-compiled code, but when it does in the future, the CPU solver will probably be faster than the GPU solver.
> 
> We also provide a V-Cycle preconditioner, which could be implemented to run in parallel on the GPU and has reasonable convergence properties. Unfortunately, the memory cost is huge, especially for large images, so it is probably not worth the trouble.


Well! Thank you very much for your source code scheme and experimental data.
In fact, the problem I encountered is that when my sample images are not so hairy, in other words, the scene I want to solve is for alpha matting and cutout of person!
In my case, using the library you provided, it seems that there is no optimization for this scenario.
Yes it is! I also found out that using _**cupy**_, even if **_CG_** is performed on the GPU, the performance is really not very surprising! CG is indeed a big bottleneck, although we still don't think about real-time performance.
In addition, I found another [library,](https://github.com/MarcoForte/closed-form-matting) which runs on the cpu, and its operating speed is acceptable.

**Comment by 99991** [comment]
Macro Forte's implementation has an optimization which improves performance if most pixels are already known. Can you share your image and the trimap so we can see if that is the reason?

Also, we recently introduced a similar optimization in version 1.1.3 for the `estimate_alpha_cf` function. It should be slightly faster if the trimap is mostly black and white. Maybe you can give it a try.

Here is an example which downloads the lemur test image/trimap and estimates the alpha matte with `estimate_alpha_cf`:

```python
import time, os
from urllib.request import urlopen
from pymatting import estimate_alpha_cf, load_image, save_image

def download_file(url, filename):
    if os.path.isfile(filename): return
    with urlopen(url) as r:
        with open(filename, "wb") as f:
            f.write(r.read())

download_file("https://github.com/pymatting/pymatting/raw/master/data/lemur/lemur.png", "lemur.png")
download_file("https://github.com/pymatting/pymatting/raw/master/data/lemur/lemur_trimap.png", "lemur_trimap.png")

image = load_image("lemur.png", "RGB")
trimap = load_image("lemur_trimap.png", "GRAY")

for test in range(3):
    t = time.perf_counter()

    alpha = estimate_alpha_cf(image, trimap)

    dt = time.perf_counter() - t

    print("test", test, "-", dt, "seconds")

save_image("alpha.png", alpha)
```

For me, this takes 0.6 seconds for the lemur image while the code you linked takes 3 seconds. Times vary a bit when run multiple times (+-0.2 seconds).

**Comment by 99991** [comment]
Closed due to inactivity. If you find that this issue still exists, feel free to re-open.
