### ISSUE TITLE
[BUG 🐛] RuntimeError: Attempted to compile AOT function without the compiler used by `numpy.distutils` present. Cannot find suitable msvc.

### ISSUE THREAD

**Issue by 99991** [pymatting/pymatting#45]
If you experience the error message

```
RuntimeError: Attempted to compile AOT function without the compiler used by `numpy.distutils` present. Cannot find suitable msvc.
```

on Windows when importing the PyMatting library, then you need to install a C compiler.

Currently, *Build Tools for Visual Studio 2019* are available here: https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019

When installing, select *Desktop Development with C++* or whatever it is called in English. The language selection is broken unfortunately.

![VisualStudioBuildTools](https://user-images.githubusercontent.com/18725165/125053081-f5524500-e0a4-11eb-878b-55e8036f128a.png)

I tried only installing specific components, but it seems like the Windows 10 SDK is required. Otherwise, `cl.exe` will fail because it can not find `basetsd.h`.

A several GB install is of course less than ideal. It would be nice if we could get rid of the dependency, which is currently required by Numba for ahead-of-time compilation.

**Comment by martinriven** [comment]
don't work with me. i have installed all the windows 10 SDK, still get this traceback
