### ISSUE TITLE
@vlsav, thanks for reporting this issue! Have you tried running `conda install gcc_linux-64 gxx_linux-64` (as suggested)?

### ISSUE THREAD

**Issue by dreamer121121** [pymatting/pymatting#46]
@vlsav, thanks for reporting this issue! Have you tried running `conda install gcc_linux-64 gxx_linux-64` (as suggested)?

_Originally posted by @tuelwer in https://github.com/pymatting/pymatting/issues/37#issuecomment-731645867_

**Comment by dreamer121121** [comment]
I have tried conda install gcc_linux-64 gxx_linux-64，but i still cant import pymattting and report the sanme info

**Comment by 99991** [comment]
Does this code also fail? If yes, then it is an issue with the Numba library and you can report it here: https://github.com/numba/numba/issues

```python3
from numba.pycc import CC

cc = CC("my_module")

# Produce useful error message (cc.verbose does not)
cc._toolchain._compiler.verbose = True

@cc.export("foo", "f8(f8)")
def foo(x):
    return 2.0 * x

cc.compile()

from my_module import foo

# Should print "2.0"
print(foo(1.0))
```

I tried installing PyMatting with the latest Fedora docker image and the following steps worked:

```bash
sudo dnf -y update
sudo dnf -y install gcc-c++ python3-pip python3-devel
pip install pymatting
python -c 'import pymatting'
```

**Comment by 99991** [comment]
I am closing this issue since there have not been any new comments, so I guess it is solved. If not, feel free to comment and I'll reopen this issue.
