### ISSUE TITLE
Trimap Values?

### ISSUE THREAD

**Issue by IQ17** [pymatting/pymatting#5]
Hi , what are the values in the trimap?

is 0 for background, 102 for uncertain, and 255 for foreground?

**Comment by 99991** [comment]
Within the space of this this library all images are expected to be floating point in range `[0, 1]`.

0 is background.
1 is foreground.
All values in-between are considered unknown.

If you are drawing trimaps in an image editing program, for example Photoshop, GIMP or PaintNet, the image will often be in range [0, 255], so there you'd have to use 0 and 255.

**Comment by IQ17** [comment]
Thanks!  Then I can put any value for the uncertain area.
