### ISSUE TITLE
[BUG 🐛]I get this BUG when I have already installed MSVC

### ISSUE THREAD

**Issue by RuifMaxx** [pymatting/pymatting#53]
![image](https://user-images.githubusercontent.com/75245181/138423055-ddb15953-ff48-44fb-ae01-cc5e29c3ed1f.png)
However, I get this BUG when I have already installed MSVC.

**Comment by RuifMaxx** [comment]
Thank you very much. However, after I upgraded pymatting. I have some issues on importing the pkg.
![image](https://user-images.githubusercontent.com/75245181/139835057-d14222ce-0153-48e5-84f9-c30aa19bacc9.png)

**Comment by 99991** [comment]
You created the file `pymatting.py`. If you run `from pymatting import cutout`, Python will try to import from your file `pymatting.py` instead of importing from the pymatting library.

**Comment by RuifMaxx** [comment]
Thanks for your reply. However, another bug I have got....
![image](https://user-images.githubusercontent.com/75245181/139837445-3ad92de2-d8f4-4beb-9e0e-48795c8c4781.png)

**Comment by 99991** [comment]
This is likely an issue with Numba and not with PyMatting. You can check your Numba version with:

```Python3
import numba
print('Numba version:', numba.__version__)
```

The current version should be around `0.54.1`.

The following code should work if your Numba installation is not broken in some way:

```Python3
from numba import njit, prange
import numpy as np

@njit("f8[:](f8[:])", cache=True, parallel=True, nogil=True)
def foo(values):
    result = np.zeros(len(values))
    for i in prange(len(values)):
        result[i] = values[i] + i
    return result

print(foo(np.random.rand(6)))

```

**Comment by RuifMaxx** [comment]
thank  you very much, I have imported the pkg successfully
