### ISSUE TITLE
[BUG 🐛] PyMatting crashes when I use it in torch dataloader.

### ISSUE THREAD

**Issue by Windaway** [pymatting/pymatting#54]
**Bug description**

I used pymatting in torch data preprocessing, but the new version of pymatting does not seem to support multi-threading. 
In addition, 1.0.4 works.

**To Reproduce**

Pymatting 1.1.4, Torch 1.10, 5900x with 3090, CUDA 11.4。 torch.dataset/dataloader. number_workers>=1.

**Comment by 99991** [comment]
Do you perhaps have a [minimal, reproducible example](https://github.com/pymatting/pymatting/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)?

**Comment by Windaway** [comment]
Sorry, my memory is burned out. It may take a few days.

**Comment by Windaway** [comment]
The cause of the failure may be a segment error caused by my memory failure.
