### ISSUE TITLE
Make PyMatting available on conda-forge

### ISSUE THREAD

**Issue by tuelwer** [pymatting/pymatting#60]
PyMatting can be made available on conda-forge by submitting a pull request to [the staged-reciples repository](https://github.com/conda-forge/staged-recipes). Detailed instructions can be found [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html).

**Comment by thewchan** [comment]
Pymatting is now installable via conda forge. https://github.com/conda-forge/pymatting-feedstock
https://anaconda.org/conda-forge/pymatting

**Comment by tuelwer** [comment]
Thanks! It seems to have worked 👍
