### ISSUE TITLE
[Question❓]

### ISSUE THREAD

**Issue by rafiqulislam21** [pymatting/pymatting#62]
How to convert choleskydecomposition object to numpy array? I want to convert return object from `pymatting.preconditioner.ichol.ichol(A)` this function.

**Comment by 99991** [comment]
Sounds like a bad idea, but if you know what you are doing, you can just use the `ichol(A).L.todense()`. Note that this is a colossal waste of memory and if all you want is to solve a linear system like $A x = L L^T x = b$, then you probably want to do `decomposition = ichol(A); x = decomposition(b)` instead, which executes backwards substitution on the sparse $L$ and $L^T$ efficiently: https://github.com/pymatting/pymatting/blob/b5f03a2c373cfe3ca6ba0f69a56e113ca3c5807d/pymatting/preconditioner/ichol.py#L177

# Disclaimer: Bad example, don't do this!

```python3
import numpy as np
import scipy.sparse
from pymatting import ichol

# Create a symmetric, positive definite matrix
n = 100
np.random.seed(0)
A = np.random.rand(n, n)
# Remove a few values of A to make it more sparse
A[np.random.rand(*A.shape) < 0.98] = 0
A += A.T + n * np.eye(n)

A_sparse = scipy.sparse.csr_matrix(A)

decomposition = ichol(A_sparse, discard_threshold=0.0)

# This constructs a scipy.sparse.csr_matrix
L_sparse = decomposition.L

# The following is not recommended because it constructs
# a dense matrix from a sparse matrix, which is a colossal waste of memory.
# If you just want to solve a linear system like
# A x = L L^T x = b,
# call the decomposition object like `x = decomposition(b)`
L_dense = L_sparse.toarray()

# Compute element-wise mean squared error to dense Cholesky decomposition
mse = np.mean(np.square(L_dense - np.linalg.cholesky(A)))

# Should be very small
print(mse)
```
