### ISSUE TITLE
Tests require missing images

### ISSUE THREAD

**Issue by jangop** [pymatting/pymatting#64]
Several tests (for example, the one in `test_estimate_alpha.py`) fail because a required image is missing:

```
FAILED tests/test_estimate_alpha.py::test_alpha - FileNotFoundError: [Errno 2] No such file or directory: 'data/input_training_lowres/GT01.png'
FAILED tests/test_laplacians.py::test_laplacians - FileNotFoundError: [Errno 2] No such file or directory: 'data/input_training_lowres/GT01.png'
FAILED tests/test_lkm.py::test_lkm - FileNotFoundError: [Errno 2] No such file or directory: 'data/input_training_lowres/GT01.png'
FAILED tests/test_preconditioners.py::test_preconditioners - FileNotFoundError: [Errno 2] No such file or directory: 'data/input_training_lowres/GT01.png'
```

Could/should `GT01.png` be included?

**Comment by 99991** [comment]
The images are not included directly for licensing reasons. They can be downloaded by running `python3 tests/download_images.py`.

See https://github.com/pymatting/pymatting#testing

**Comment by jangop** [comment]
Oh. Thanks.

Would it be okay to have them downloaded automatically?

**Comment by 99991** [comment]
For legal reasons it is probably better to not download things unless the user wanted to do so. But I am not a lawyer and law is different all over the world, so who knows.

**Comment by jangop** [comment]
Yes...

Maybe I'll have pytest issue a warning for people such as myself who miss that line in the readme.

**Comment by tuelwer** [comment]
Closed by https://github.com/pymatting/pymatting/pull/89
