### ISSUE TITLE
[Question❓]is there a way to speed it up？

### ISSUE THREAD

**Issue by JSHZT** [pymatting/pymatting#65]
Hey！This tool can bring me very good results, but I did statistics, and it took me nearly 10 minutes to process 1,000 images without counting the IO time. 1,000 images generally correspond to a 30-second video. This efficiency is Not ideal, looking forward to reply

**Comment by 99991** [comment]
The algorithms are about as fast as they can get, so there is not much to be gained there if you run it on a single CPU core. We are working on a different approach which might be faster, but it will take a few more months until it is finished.

Until then, you could try running this in parallel by processing each image independently.

You could also try to [initialize the solver](https://github.com/pymatting/pymatting/blob/b5f03a2c373cfe3ca6ba0f69a56e113ca3c5807d/pymatting/solver/cg.py#L7) with the alpha matte of the previous frame. If the frames and alpha mattes are very similar, this might help a bit.

Lastly, you could reduce the [convergence threshold](https://github.com/pymatting/pymatting/blob/b5f03a2c373cfe3ca6ba0f69a56e113ca3c5807d/pymatting/solver/cg.py#L9) of the the conjugate gradient solver, but that would also reduce quality.

Could you share a few images and trimaps? I could see if I can cobble together a quick script.

**Comment by JSHZT** [comment]
Thank you for your suggestion! The statistical results in the problem description are what I did when I tried to use the same alpha mask to initialize the solver, because the frames and alpha mattes are very similar, and the foreground is almost in one area, but because of this, I expanded the unknown area , to prevent certain images from causing problems due to the white area of trimap covering the edge.
How can I share pictures with you? I don't want to make these pictures public, because it involves other people's information.
Is it possible to use the GPU or implement it in a compiled language such as C++ to achieve acceleration?

**Comment by 99991** [comment]
> How can I share pictures with you privately, I don't want to make these pictures public, because it involves other people's information.

You can mail a few images (4 consecutive frames are probably enough) to pymattingissue65@asdf10.com and I will delete them once it works well enough. Additionally, you could also paint over the faces just to make sure that privacy is preserved. Also include the trimaps and an alpha matte so I know how things are supposed to look like.

Which alpha matting method are you currently using?

> Is it possible to use the GPU or implement it in a compiled language such as C++ to achieve acceleration?

The algorithms are already accelerated with Numba, which compiles the Python code with LLVM. C++ would be a tiny bit faster, but is probably not worth the effort.

GPU could be faster, but it would require some work. We are looking at perhaps replacing Numba with  [taichi lang](https://github.com/taichi-dev/taichi/) because GPU support looks quite good, but did not have the time jet.

**Comment by JSHZT** [comment]
The method I use is "cf", and I will send the material you need to the mailbox soon, looking forward to your solution!

**Comment by 99991** [comment]
Your images all had a greenscreen background, which means that a trimap with smaller unknown region can be extracted automatically. If the trimap has fewer unknown values, the alpha estimation will run faster. But you might have to fiddle with the configurable parameters a bit to make it work with all images.

I also used a ThreadPool for parallelism. Initializing the alpha matte for the conjugate gradient solver did not help, so I left it out.

You can make it a few percent faster still by choosing an image file format which does not require compression, but that depends on what your other tools support. TIFF might work.

```python3
from pymatting import *
import numpy as np
import time
import os
from multiprocessing.pool import ThreadPool
from PIL import Image

image_filenames = ["000616.png", "000617.png", "000618.png", "000619.png"]

start_time = time.perf_counter()

# pixels are classified as background if they match the top-left pixel to within 0.01
background_color_threshold = 0.01
# background mask is shrunk to not include foreground by accident
# increase value for more transparent objects
background_shrink_radius = 5
# foreground mask is the inverse of background mask, shrunk by radius
foreground_shrink_radius = 5
# slightly faster with larger epsilon values, but alpha matte will be less detailed
epsilon = 1e-5

def shrink(mask, radius):
    # shrink mask by radius, similar to morphological erosion
    # https://en.wikipedia.org/wiki/Erosion_(morphology)
    mask = mask.astype(np.float64)
    mask = np.pad(mask, ((radius, radius), (radius, radius)), mode="edge")
    mask = boxfilter(mask, radius=radius)
    mask = mask[radius:-radius, radius:-radius]
    mask = (mask > 0.99).astype(np.float64)
    return mask

def process_image(filename):
    print("Processing", filename)
    image = load_image(filename, "RGB")

    background_color = image[0, 0]

    rough_bg_mask = np.mean(np.square(image - background_color), axis=2) < background_color_threshold

    is_bg = shrink(rough_bg_mask, background_shrink_radius)
    is_fg = shrink(1.0 - rough_bg_mask, foreground_shrink_radius)

    trimap = 0.5 + 0.5 * is_fg - 0.5 * is_bg

    alpha = estimate_alpha_cf(image, trimap, laplacian_kwargs=dict(epsilon=epsilon))

    foreground = estimate_foreground_ml(image, alpha)

    cutout = stack_images(foreground, alpha)

    save_image(os.path.join("cutout", filename + ".tiff"), cutout)

with ThreadPool() as pool:
    pool.map(process_image, image_filenames)

elapsed_time = time.perf_counter() - start_time

print(elapsed_time, "seconds")
```

**Comment by JSHZT** [comment]
Thanks for your help, the speed has been optimized to a certain extent.
