### ISSUE TITLE
здравствуйте Изображения не включены напрямую по причинам лицензирования  а если по кнопки  это вреде не нарушает лицензирования  [Question❓]

### ISSUE THREAD

**Issue by egoorr** [pymatting/pymatting#70]
![b96becd4-15a7-4f18-9423-45e1d7f78d9c_cleanup](https://github.com/pymatting/pymatting/assets/142255641/e9e89036-7e11-44d2-8192-854f746a5b1d)

**Comment by 99991** [comment]
Sorry, I do not speak that language. Please try again in English.

**Comment by egoorr** [comment]
Hello, the images are not included directly for licensing reasons, and if the buttons are like in the picture, it does not violate licensing.
