### ISSUE TITLE
[Question❓]how can i improve image edge quality

### ISSUE THREAD

**Issue by babyta** [pymatting/pymatting#72]
![alpha](https://github.com/pymatting/pymatting/assets/37787795/fb3a6688-37e1-4231-8ca9-55e3c1058380)
![177074](https://github.com/pymatting/pymatting/assets/37787795/72884714-7c74-4b34-8fe9-4f3a7764d0ec)
The edges of this kind of image are not clear, and the resulting alpha image is not good.

**Comment by tuelwer** [comment]
Could you please also provide your code and the input trimap?

**Comment by babyta** [comment]
Thanks for your reply, I digested it

**Comment by babyta** [comment]
Hello author, I still have a question, which may be beyond the scope of matting research. For example, in the application of background replacement, if you use a ready-made segmentation algorithm such as SAM, the extracted edges are not accurate, which will affect the effect of background replacement. , what traditional method can I use to optimize this edge. I think it will be helpful to study your source code. thank you for your reply.

**Comment by 99991** [comment]
@danielgatis had a similar issue in the past: https://github.com/pymatting/pymatting/issues/33

He is currently using binary erosion to create a trimap from the segmentation followed by closed-form alpha matting: https://github.com/danielgatis/rembg/blob/main/rembg/bg.py

**Comment by babyta** [comment]
Hi, I have tested danielgatis's work, but it doesn't work as well as some websites, such as photoroom.com. I'm very curious about how Photoroom's cutout can be so relatively perfect.

**Comment by 99991** [comment]
My guess would be that they are using https://github.com/MarcoForte/FBA_Matting or a variation of it trained on an in-house dataset since @MarcoForte works there now. Perhaps he can tell. But I think it might be a company secret.

**Comment by babyta** [comment]
Thanks a lot, I'll look into it！

**Comment by babyta** [comment]
Hello, do you have any recommendations for edge smoothing algorithms? I find this very important. I have learned about the algorithm in the connection, which belongs to the matting algorithm based on deep learning. If the segmented edges have more burrs, there is still no good way to smooth these edges to make them closer to the real object.

**Comment by 99991** [comment]
> If the segmented edges have more burrs, there is still no good way to smooth these edges to make them closer to the real object.

If you have a binary segmentation and want to smooth the edges of that binary segmentation in a way that follows the object (also called edge-preserving smoothing), then you might find the Guided Filter useful, see e.g. [Figure 4 of the Paper "Fast Guided Filter"](https://arxiv.org/pdf/1505.00996.pdf). Closed-form alpha matting can also be interpreted as iterative application of the guided filter. You can probably find many implementations of that algorithm online,

**Comment by 99991** [comment]
According to [this video](https://www.youtube.com/watch?v=u2UBvsZv954&t=306s), they have two different AI models and a different method from ReMask 5 if you select "Contrast", but I do not know what method that is. My guess would be something like [Soft Scissors](https://dl.acm.org/doi/pdf/10.1145/1275808.1276389). Currently, PyMatting does not (yet?) implement any of those methods.

**Comment by babyta** [comment]
thank you！
