### ISSUE TITLE
[Question❓] next release?

### ISSUE THREAD

**Issue by PeterJCLaw** [pymatting/pymatting#73]
Thanks for this project, it's really useful.

I was wondering what the project's timelines might be for a future release? We're particularly interested in the shared matting features added in July, yet they haven't made it to PyPI yet. I was wondering whether there was any reason for that/if there's anything the community can do to help?

**Comment by 99991** [comment]
We are happy to know that this project is useful to you! We have just published a new release:

* https://pypi.org/project/PyMatting/
* https://github.com/pymatting/pymatting/releases/tag/v1.1.10

Personally, I found that shared matting was not quite perfect at all times. But I am glad to hear that you are interested in it! This makes me believe that we should gather some information about the actual use cases for PyMatting so we know what people are looking for. Would you like to tell us a bit about your use case here? :point_right:  https://github.com/pymatting/pymatting/issues/74
