### ISSUE TITLE
[Question❓] pymatting is slow running on A100

### ISSUE THREAD

**Issue by ynie** [pymatting/pymatting#78]
Hello all, very cool project. Just want to double check if pymatting is downloading any models on demand when the first time importing this library. For some reason, it takes ~30s to import these three lines on a clean Docker Build:

```
    from pymatting.alpha.estimate_alpha_cf import estimate_alpha_cf
    from pymatting.foreground.estimate_foreground_ml import estimate_foreground_ml
    from pymatting.util.util import stack_images
```

What did I miss? Thank you!

**Comment by 99991** [comment]
PyMatting uses the [Numba](https://github.com/numba/numba) library for JIT compilation. All JIT-compiled functions will be cached to make repeated calls are faster. I can think of three options to avoid repeated JIT compilation:

- You could try preserving the cache directory. You can set the environment variable `NUMBA_CACHE_DIR` to specify its location manually. https://numba.pydata.org/numba-doc/latest/reference/envvars.html#envvar-NUMBA_CACHE_DIR
- You could import the library when building the docker container. Make sure to import and run as the same user with the same hardware.
- You could wrap PyMatting as a web service and keep the container alive forever. This way, you do not repeatedly import it.

You also mentioned that you are using an A100 GPU. Currently, only a few foreground estimation methods can make use of GPUs, for example `estimate_foreground_ml_cupy` if you install CuPy.

* https://pymatting.github.io/foreground.html#estimate_foreground_ml_cupy
* https://github.com/pymatting/pymatting/blob/master/pymatting/foreground/estimate_foreground_ml_cupy.py

However, CuPy is very slow on first import. I do not know whether it can be cached.

**Comment by ynie** [comment]
Thank you!

**Comment by 99991** [comment]
Glad I could help!

If those solutions should turn out to not work for you, we could think about other ways to solve it. For example, I considered replacing Numba with https://github.com/taichi-dev/taichi or a different JIT-compiler, but that would require rewriting most of PyMatting and might introduce backwards-compatibility issues, so I am not sure whether it is worth the effort.
