### ISSUE TITLE
Cant find "tests/download_images.py"

### ISSUE THREAD

**Issue by BatDev0** [pymatting/pymatting#8]
When I try to do the python tests/download_images.py It gives me the following error.

`can't open file 'tests/download_images.py': [Errno 2] No such file or directory`

I am in my Python Projects folder. So Like `src/github/BatDev0/pymatting` This is where i do all my python tests and projects. Do i have to do the command in a other folder?

**Comment by tuelwer** [comment]
Are you sure that you are in the main directory and not in ```pymatting/pymatting```?
