### ISSUE TITLE
too small images in building the knn-laplacian[BUG 🐛]

### ISSUE THREAD

**Issue by IliasIhadian** [pymatting/pymatting#83]
**Bug description** 

When you insert an image with fewer than k pixels, it throws an error:
IndexError: index 5042262256 is out of bounds for axis 0 with size 16

**To Reproduce**

```python
knn_laplacian(image)
````

With an image which is 4x4 Pixel.

**Expected behavior**

I believe it would be better to throw out an error message which kindly reminds you to use bigger pictures 
or to just automatically change the k to a smaller number. :)

**Comment by 99991** [comment]
You are correct! Thank you for finding this issue!

I think the best solution would be to raise a `ValueError` with a meaningful error message when `self.shuffled_data_points.shape[0]` is less than `k` somewhere at the beginning of the `query` function of the `KDTree` object:

https://github.com/pymatting/pymatting/blob/a073421a31afd0d53b7ff387ad2b361645b446be/pymatting/util/kdtree.py#L312
