### ISSUE TITLE
Error in local installation

### ISSUE THREAD

**Issue by vandesa003** [pymatting/pymatting#9]
I am trying to install the repo through:
`git clone https://github.com/pymatting/pymatting.git`
`cd pymatting`
`pip install .`
but I met the error below:

```Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    long_description=load_text("README.md"),
  File "setup.py", line 6, in load_text
    return f.read()
  File "/ldap_home/bohang.li/.conda/envs/pymatting/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3305: ordinal not in range(128)```

**Comment by 99991** [comment]
Maybe your system has an unusual default for text encoding.

Could you try changing the default encoding in [line 5 of the `load_text` function in setup.py](https://github.com/pymatting/pymatting/blob/c6a48e2887e61d1f074a830e69b52c34fea9d7af/setup.py#L5)?

```python3
with open(path, encoding="utf-8") as f:
```

**Comment by vandesa003** [comment]
@99991 Thanks for your quick response. The problem solved. By the way, do you have plan to provide auto trimap generation? Currently, pymatting relies on an extra trimap image. It will be more convenient to use if there is an option I can choose to generate a trimap automatically by maybe simple erosion and dilation.

**Comment by 99991** [comment]
That's great to hear!

We are not currently considering adding automatic trimap generation. Maybe in the far future.
